language: r
r:
  - oldrel
  - release
  - devel
cache: packages

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    recipients:
      - fabian.scheipl@stat.uni-muenchen.de
    on_success: change
    on_failure: always
