language: r
sudo: required

r:
  - oldrel
  - release
  - devel
cache: packages
r_build_args: "--compact-vignettes='gs+qpdf'"
r_check_args: "--as-cran --run-donttest --no-vignettes --no-build-vignettes"

#before_install:
    #- sudo apt-get -qq install gcc-4.8
    #- sudo apt-get -qq install g++-4.8
    #- sudo apt-get install -qq gfortran-4.8
    #- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90
    #- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
    #- sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-4.8 90

bioc_required: true
bioc_packages:
  - BiocGenerics
  - graph
  - Rgraphviz


after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    recipients:
      - fabian.scheipl@stat.uni-muenchen.de
    on_success: change
    on_failure: always
